#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/netmonitor

start_service() {
    local enabled
    
    config_load 'netmonitor'
    config_get_bool enabled general enabled 0
    
    if [ "$enabled" -eq 1 ]; then
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param respawn
        procd_close_instance
    fi
}

service_triggers() {
    procd_add_reload_trigger "netmonitor"
}

reload_service() {
    stop
    start
}